"""Unit conversion — re-exported from the shared ``lab_commons`` (extracted, plan-lab-commons-standalone.md §3).

The pint<->pydantic machinery (tier 1, ``lab_commons.units``) and the EM quantity vocabulary
(tier 2, ``lab_commons.em``) were extracted to the standalone ``lab-commons`` package. motronics'
``Annotated`` design is the canonical one (maintainer, "全面采用 Annotated design"), so this module
DEFINES NO quantity machinery of its own — it is a re-export of both tiers' public surface,
resolving every name to the ONE shared definition in lab_commons (pinned by
``tests/unit/utils/test_no_quantities_refork.py``). optimi-lab's own ``PydanticQuantity``
core-schema design has been retired in favor of this.

``pydantic_config_dict_with_q_case_insensitive`` is the one optimi-specific addition kept here: a
``ConfigDict`` variant (case-sensitive strings) lab_commons has no counterpart for, used by
optimi-lab's ``Utils``/``Config`` models.
"""

from lab_commons.em import (
    CONSTANTS,
    Q_0A,
    Q_0H,
    Q_0J,
    Q_0T,
    Q_0W,
    Q_1A,
    Q_1J,
    Q_1N,
    Q_1T,
    Q_1V,
    Q_1W,
    Q_5A,
    Q_10A,
    Q_20A,
    Q_100A,
    AngleSpeedType,
    AngleType,
    AreaType,
    Cartesian2DPoint,
    Cartesian2DPoint_Array,
    CurrentDensityType,
    CurrentType,
    DensityType,
    ElecConductivityType,
    EnergyType,
    FluxDensityType,
    FluxLinkageType,
    ForceType,
    FrequencyType,
    InductanceType,
    LengthType,
    MagFieldIntensityType,
    MagVectorPotentialType,
    MassType,
    MMFType,
    PermeabilityType,
    PerTemperatureType,
    Polar2DPoint,
    Polar2DPoint_Array,
    PowerPerMassType,
    PowerType,
    Q_0A_per_m,
    Q_0A_per_mm2,
    Q_0deg,
    Q_0degC,
    Q_0Hz,
    Q_0kg,
    Q_0mm,
    Q_0mm2,
    Q_0mm3,
    Q_0MS_per_m,
    Q_0Nm,
    Q_0ohm,
    Q_0ohm_m,
    Q_0rpm,
    Q_0s,
    Q_0Wb,
    Q_0Wb_per_m,
    Q_1A_per_mm2,
    Q_1At,
    Q_1Hz,
    Q_1kg,
    Q_1m2,
    Q_1mm,
    Q_1mm2,
    Q_1mm3,
    Q_1Nm,
    Q_1ohm,
    Q_1rad,
    Q_1Wb,
    Q_1Wb_per_m,
    Q_2pi,
    Q_10Wb,
    Q_20degC,
    Q_50Hz,
    Q_90deg,
    Q_180deg,
    Q_360deg,
    Q_list2array,
    ResistanceType,
    ResistivityType,
    TemperatureType,
    TimeType,
    TorqueType,
    VoltageType,
    VolumeType,
    array2list_2Dpoint,
    is_equal_2DPoint,
)
from lab_commons.units import (
    Q_,
    BaseModel_with_q,
    PintQuantityType,
    PydanticQuantity,
    get_quantity_type,
    pydantic_config_dict_with_q,
    ureg,
)
from pint import Unit
from pydantic import ConfigDict

__all__ = [
    'CONSTANTS',
    'Q_',
    'Q_0A',
    'Q_0H',
    'Q_0J',
    'Q_0T',
    'Q_0W',
    'Q_1A',
    'Q_1J',
    'Q_1N',
    'Q_1T',
    'Q_1V',
    'Q_1W',
    'Q_5A',
    'Q_10A',
    'Q_20A',
    'Q_100A',
    'AngleSpeedType',
    'AngleType',
    'AreaType',
    'BaseModel_with_q',
    'Cartesian2DPoint',
    'Cartesian2DPoint_Array',
    'CurrentDensityType',
    'CurrentType',
    'DensityType',
    'ElecConductivityType',
    'EnergyType',
    'FluxDensityType',
    'FluxLinkageType',
    'ForceType',
    'FrequencyType',
    'InductanceType',
    'LengthType',
    'MMFType',
    'MagFieldIntensityType',
    'MagVectorPotentialType',
    'MassType',
    'PerTemperatureType',
    'PermeabilityType',
    'PintQuantityType',
    'Polar2DPoint',
    'Polar2DPoint_Array',
    'PowerPerMassType',
    'PowerType',
    'PydanticQuantity',
    'Q_0A_per_m',
    'Q_0A_per_mm2',
    'Q_0Hz',
    'Q_0MS_per_m',
    'Q_0Nm',
    'Q_0Wb',
    'Q_0Wb_per_m',
    'Q_0deg',
    'Q_0degC',
    'Q_0kg',
    'Q_0mm',
    'Q_0mm2',
    'Q_0mm3',
    'Q_0ohm',
    'Q_0ohm_m',
    'Q_0rpm',
    'Q_0s',
    'Q_1A_per_mm2',
    'Q_1At',
    'Q_1Hz',
    'Q_1Nm',
    'Q_1Wb',
    'Q_1Wb_per_m',
    'Q_1kg',
    'Q_1m2',
    'Q_1mm',
    'Q_1mm2',
    'Q_1mm3',
    'Q_1ohm',
    'Q_1rad',
    'Q_2pi',
    'Q_10Wb',
    'Q_20degC',
    'Q_50Hz',
    'Q_90deg',
    'Q_180deg',
    'Q_360deg',
    'Q_list2array',
    'ResistanceType',
    'ResistivityType',
    'TemperatureType',
    'TimeType',
    'TorqueType',
    'Unit',
    'VoltageType',
    'VolumeType',
    'array2list_2Dpoint',
    'get_quantity_type',
    'is_equal_2DPoint',
    'pydantic_config_dict_with_q',
    'pydantic_config_dict_with_q_case_insensitive',
    'ureg',
]

pydantic_config_dict_with_q_case_insensitive = ConfigDict(
    str_to_lower=False,
    strict=True,
    extra='forbid',
    arbitrary_types_allowed=True,
)
