"""HOOKS-ARE-WIRED, for THIS checkout -- and the gap was VIOLATED, not merely unenforced.

MEASURED 2026-09-16: `.pre-commit-config.yaml` here declares 19 hooks at the `pre-commit` stage and
**ZERO were installed** in the directory git actually consults. Every commit through this checkout
had run none of them while the tree read as guarded. The adoption file's previous reason -- that
optimi-lab "has no hooks directory" -- was false in the way that matters most: the DECLARATION was
here all along and nothing asked whether it had been acted on.

THE SPLIT. `lab_commons.dev.hook_install` owns the mechanism: it resolves the hooks directory by
ASKING GIT rather than string-building `.git/hooks` (the arm that a worktree and a `core.hooksPath`
redirect both break), reads the declared set off the configuration rather than taking a caller's
word for it, and separates `declared-but-absent` from `present-but-stale` from
`present-but-not-pre-commit's`. What belongs to optimi-lab is the tree being asked about and the
named set of stages it declares.

WHAT THIS PROVES, EXACTLY: a live pre-commit shim, generated by pre-commit, pointing at THIS
configuration, in the matching hook-type slot. Strictly weaker than "these hooks pass", and it says
nothing about whether a hook's own entry resolves.

THE REMEDY IS DERIVED. The failure message ends with `install_command`'s argv, built from the
configuration itself, so a stage added there cannot leave this file telling a reader to install a
subset -- the half-configured state this guard exists to make visible, one level up.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Final

from lab_commons.dev.hook_install import (
    ABSENT,
    DEFAULT_CONFIG_NAME,
    INSTALLED,
    PROTECTED,
    UNPROTECTED,
    declared_stages,
    generated_hook,
    hook_installation,
    hooks_dir,
    install_command,
)

#: The operator's git, resolved once: a bare name lets PATH decide which one runs.
_GIT = shutil.which('git') or 'git'

#: THE TREE UNDER TEST, not the working directory: a scan rooted at the CWD answers, plausibly,
#: about somebody else's checkout.
_ROOT: Final = Path(__file__).resolve().parents[2]

#: The floor on this scan, and it is the SET rather than a count -- a count cannot say WHICH stage
#: moved. A configuration that parsed to nothing would let this file agree with any tree at all.
#: MEASURED 2026-09-16. Two-sided: a stage added and not installed reds, a stage removed reds.
DECLARED_STAGES: Final = frozenset({'pre-commit'})


def test_this_repository_declares_hooks_at_all() -> None:
    """CONTROL FOR THE INSTRUMENT. A guard reading an empty declaration is watching nothing."""
    report = hook_installation(_ROOT, config_name=DEFAULT_CONFIG_NAME)
    assert report.config is not None, f'no {DEFAULT_CONFIG_NAME} at {_ROOT}; this guard is watching nothing'
    assert {stage.stage for stage in report.stages} == DECLARED_STAGES, (
        f'the declared stages are {sorted(stage.stage for stage in report.stages)}, not '
        f'{sorted(DECLARED_STAGES)}. Both directions matter: a new stage must be installed before it '
        f'counts, and a deleted one must leave this pin in the same edit.'
    )
    assert all(stage.hook_ids for stage in report.stages), 'a stage declaring no hook id is an unread configuration'


def test_every_hook_this_repository_declares_is_installed() -> None:
    """THE PROPERTY. Green means the commits through this checkout are guarded for real."""
    report = hook_installation(_ROOT, config_name=DEFAULT_CONFIG_NAME)
    listing = '\n  '.join(f'{stage.stage:<12} {stage.status:<24} {stage.detail}' for stage in report.failing)
    remedy = 'python ' + ' '.join(install_command(_ROOT, config_name=DEFAULT_CONFIG_NAME))
    assert report.verdict == PROTECTED, (
        f'{len(report.failing)} of {len(report.stages)} declared stage(s) are not live in '
        f'{report.hooks_dir}:\n  {listing}\n\n'
        f'Every commit through this checkout ran none of them, while the tree says they guard it. '
        f'Install them -- the hooks directory is shared by every worktree on this box, so this is a '
        f'deliberate act and never a silent repair:\n  {remedy}\n'
    )


def test_the_hooks_directory_is_the_one_git_will_consult() -> None:
    """A guard that string-built `.git/hooks` answers about a directory git may not be using."""
    resolved = hooks_dir(_ROOT)
    assert resolved.is_dir(), f'{resolved} is not a directory'
    named = subprocess.run(
        [_GIT, '-C', str(_ROOT), 'rev-parse', '--git-path', 'hooks'],
        capture_output=True,
        text=True,
        check=True,
        timeout=60,
    ).stdout.strip()
    assert resolved.resolve() in (Path(named).resolve(), (_ROOT / named).resolve())


def test_this_guard_can_go_both_ways(tmp_path: Path) -> None:
    """PLANTED CONTROL, in a real repository carrying THIS repository's own configuration.

    A guard that is green on the real tree proves nothing by being green -- it could be asserting a
    constant. Both states are planted and driven through the same function the property uses.
    """
    fixture = tmp_path / 'checkout'
    fixture.mkdir()
    subprocess.run([_GIT, 'init', '-q', str(fixture)], check=True, capture_output=True, timeout=60)
    (fixture / DEFAULT_CONFIG_NAME).write_text(
        (_ROOT / DEFAULT_CONFIG_NAME).read_text(encoding='utf-8'), encoding='utf-8'
    )

    absent = hook_installation(fixture, config_name=DEFAULT_CONFIG_NAME)
    assert absent.verdict == UNPROTECTED
    assert {stage.status for stage in absent.stages} == {ABSENT}

    directory = hooks_dir(fixture)
    directory.mkdir(parents=True, exist_ok=True)
    for stage in absent.stages:
        (directory / stage.stage).write_text(
            generated_hook(config_name=DEFAULT_CONFIG_NAME, hook_type=stage.stage), encoding='utf-8'
        )

    installed = hook_installation(fixture, config_name=DEFAULT_CONFIG_NAME)
    assert installed.verdict == PROTECTED
    assert {stage.status for stage in installed.stages} == {INSTALLED}


def test_a_foreign_hook_is_not_an_installed_one(tmp_path: Path) -> None:
    """The status that exists because "a file is in the slot" is not the question being asked.

    Re-installing over a hand-written hook DELETES it, so "somebody else's hook" and "pre-commit's
    hook, stale" are two findings with two different remedies and may not be collapsed into one.
    """
    fixture = tmp_path / 'checkout'
    fixture.mkdir()
    subprocess.run([_GIT, 'init', '-q', str(fixture)], check=True, capture_output=True, timeout=60)
    (fixture / DEFAULT_CONFIG_NAME).write_text(
        (_ROOT / DEFAULT_CONFIG_NAME).read_text(encoding='utf-8'), encoding='utf-8'
    )
    directory = hooks_dir(fixture)
    directory.mkdir(parents=True, exist_ok=True)
    (directory / 'pre-commit').write_text('#!/bin/sh\necho mine\n', encoding='utf-8')

    statuses = {stage.status for stage in hook_installation(fixture, config_name=DEFAULT_CONFIG_NAME).stages}
    assert statuses == {'present-but-not-pre-commits'}
    assert hook_installation(fixture, config_name=DEFAULT_CONFIG_NAME).verdict == UNPROTECTED


def test_the_remedy_is_read_off_the_configuration_rather_than_restated() -> None:
    """A remedy naming a SUBSET of the stages leaves one quietly uninstalled -- measured elsewhere."""
    stages = set(declared_stages(_ROOT / DEFAULT_CONFIG_NAME))
    command = install_command(_ROOT, config_name=DEFAULT_CONFIG_NAME)
    named = {command[index + 1] for index, arg in enumerate(command) if arg == '-t'}
    assert named == stages, f'the install command names {sorted(named)} for a configuration declaring {sorted(stages)}'
