"""HOOKS-ARE-WIRED, for THIS checkout -- and the gap was VIOLATED, not merely unenforced.

MEASURED 2026-09-16: `.pre-commit-config.yaml` here declares 19 hooks at the `pre-commit` stage and
**ZERO were installed** in the directory git actually consults. Every commit through this checkout
had run none of them while the tree read as guarded. The adoption file's previous reason -- that
optimi-lab "has no hooks directory" -- was false in the way that matters most: the DECLARATION was
here all along and nothing asked whether it had been acted on.

WHAT THIS PROVES, EXACTLY: a live pre-commit shim, generated by pre-commit, pointing at THIS
configuration, in the matching hook-type slot. Strictly weaker than "these hooks pass", and it says
nothing about whether a hook's own entry resolves.

THE BODY IS THE FAMILY'S AS OF 2026-09-17, AND HALF OF IT ALREADY WAS.
`lab_commons.dev.hook_install` has owned the MEASUREMENT since 2026-09-16: it resolves the hooks
directory by ASKING GIT rather than string-building `.git/hooks` (the arm a worktree and a
`core.hooksPath` redirect both break), reads the declared set off the configuration rather than
taking a caller's word for it, and separates `declared-but-absent` from `present-but-stale` from
`present-but-not-pre-commit's`. What was still forked three ways was the six-arm TEST around it, so
that is what moved to `lab_commons.dev.famtests.hookinstall`. What belongs to optimi-lab is the tree
being asked about and the named set of stages it declares.

ONE ARM OF THE FORKED COPY IS GONE AND ITS ABSENCE IS THE FINDING. All three copies spelled
`assert all(stage.hook_ids for stage in report.stages)` -- "a stage declaring no hook id is an unread
configuration". That check CANNOT FAIL: `declared_stages` groups hook ids BY stage, so a stage is in
the report only because an id put it there, and the empty case it guards is unreachable through the
only path that builds one. The real version of that concern is one layer down and already
mechanised: the parser RAISES on a configuration it could not read rather than reporting it empty. A
guard no fixture can red is prose with an `assert` in front of it, so it was not ported and is not
replaced.

THE REMEDY IS DERIVED. The failure message ends with `install_command`'s argv, built from the
configuration itself, so a stage added there cannot leave this file telling a reader to install a
subset -- the half-configured state this guard exists to make visible, one level up.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

from lab_commons.dev.famtests import hookinstall
from lab_commons.dev.hook_install import DEFAULT_CONFIG_NAME

#: THE TREE UNDER TEST, not the working directory: a scan rooted at the CWD answers, plausibly,
#: about somebody else's checkout.
_ROOT: Final = Path(__file__).resolve().parents[2]

#: The floor on this scan, and it is the SET rather than a count -- a count cannot say WHICH stage
#: moved. A configuration that parsed to nothing would let this file agree with any tree at all.
#: MEASURED 2026-09-16. Two-sided: a stage added and not installed reds, a stage removed reds.
#:
#: `commit-msg` ARRIVED ON 2026-09-17 AND THE GAP IT NAMES WAS ALWAYS HERE. Adopting the family
#: `.pre-commit-config.yaml` base spells commitizen's stage out -- `stages: [commit-msg]` -- where
#: this repo had left it implicit. WHICH stage commitizen runs at did not change: MEASURED through
#: `pre_commit.repository.all_hooks` before and after, it resolved to `commit-msg` both times,
#: because the upstream manifest already said so. What changed is that this guard reads the
#: CONFIGURATION TEXT, so an implicit stage was invisible to it -- and the commit-msg shim had never
#: been installed, which means every commit message through this checkout had gone unchecked while
#: the tree read as guarded. The adoption did not create the stage, it made the hole legible, and
#: the hole was closed in the same commit with the argv the failure message below derives.
DECLARED_STAGES: Final = frozenset({'commit-msg', 'pre-commit'})


def test_this_repository_declares_hooks_at_all() -> None:
    """CONTROL FOR THE INSTRUMENT, and the two-sided pin, in one arm because they are one question.

    A guard reading an empty declaration is watching nothing, and a guard reading a declaration it
    was not pinned against is watching something else.
    """
    hookinstall.assert_stages_are_declared(root=_ROOT, config_name=DEFAULT_CONFIG_NAME, declared_stages=DECLARED_STAGES)


def test_every_hook_this_repository_declares_is_installed() -> None:
    """THE PROPERTY. Green means the commits through this checkout are guarded for real."""
    hookinstall.assert_declared_hooks_are_installed(root=_ROOT, config_name=DEFAULT_CONFIG_NAME)


def test_the_hooks_directory_is_the_one_git_will_consult() -> None:
    """A guard that string-built `.git/hooks` answers about a directory git may not be using."""
    hookinstall.assert_hooks_dir_is_the_one_git_consults(root=_ROOT)


def test_this_guard_can_go_both_ways(tmp_path: Path) -> None:
    """PLANTED CONTROL, in a real repository carrying THIS repository's own configuration.

    A guard that is green on the real tree proves nothing by being green -- it could be asserting a
    constant. Both states are planted and driven through the same function the property uses, and
    the configuration is COPIED rather than invented so the control plants what the real reader
    reads.
    """
    hookinstall.assert_the_guard_can_go_both_ways(root=_ROOT, config_name=DEFAULT_CONFIG_NAME, scratch=tmp_path)


def test_a_foreign_hook_is_not_an_installed_one(tmp_path: Path) -> None:
    """The status that exists because "a file is in the slot" is not the question being asked.

    Re-installing over a hand-written hook DELETES it, so "somebody else's hook" and "pre-commit's
    hook, stale" are two findings with two different remedies and may not be collapsed into one.

    THE PLANT IS DERIVED FROM THE CONFIGURATION, never spelled. A fixture that hard-coded
    `pre-commit` was measuring one stage and reporting about all of them, which the 2026-09-17
    adoption caught: the base spells commitizen's `commit-msg` out, a second stage appeared, and the
    unplanted one answered `declared-but-absent` -- a TRUE finding about the fixture and a false one
    about the status under test.
    """
    hookinstall.assert_a_foreign_hook_is_not_installed(root=_ROOT, config_name=DEFAULT_CONFIG_NAME, scratch=tmp_path)


def test_the_remedy_is_read_off_the_configuration_rather_than_restated() -> None:
    """A remedy naming a SUBSET of the stages leaves one quietly uninstalled -- measured elsewhere."""
    hookinstall.assert_the_remedy_is_derived(root=_ROOT, config_name=DEFAULT_CONFIG_NAME)
